# Generated by Django 5.0.2 on 2024-06-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidalApp', '0002_panier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
