# Generated by Django 5.0.2 on 2024-06-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KidalApp', '0004_panier_lignepanier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='LignePanier',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
