# Generated by Django 5.0.2 on 2024-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KidalApp', '0008_panier_commanderpanier_panieritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
