# Generated by Django 5.0.2 on 2024-06-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0002_conge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamenApp.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=50)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamenApp.employe')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamenApp.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamenApp.employe')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamenApp.voiture')),
            ],
        ),
    ]
